import Head from "next/head";
import { useEffect, useRef, useState } from "react";

import img1 from "../public/images/1.jpg";
import img2 from "../public/images/2.jpg";
import img3 from "../public/images/3.jpg";
import img4 from "../public/images/4.jpg";
import img5 from "../public/images/5.jpg";
import img6 from "../public/images/6.jpg";

const images = [img1, img2, img3, img4, img5, img6];

export default function Home() {
	const [imageIndex, setImageIndex] = useState(0);

	const imageRef = useRef<HTMLImageElement>(null);

	useEffect(() => {
		imageRef.current?.scrollIntoView({ behavior: "smooth" });
	}, [imageIndex]);

	function changeCurrentImageIndex(offset: number) {
		if (imageIndex === 0 && offset === -1) {
			setImageIndex(images.length - 1);
			return;
		}

		if (imageIndex === images.length - 1 && offset === 1) {
			setImageIndex(0);
			return;
		}

		setImageIndex((i) => i + offset);
	}

	return (
		<>
			<Head>
				<title>Simple Carousel</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex h-screen flex-col items-center justify-center gap-8">
				<h1 className="text-center font-serif text-4xl font-bold">
					Simple Carousel
				</h1>

				<div className="relative mx-2 flex max-w-xl snap-x snap-mandatory items-center gap-4 overflow-auto rounded-md sm:overflow-hidden">
					{images.map((img, index) => (
						<img
							ref={imageIndex === index ? imageRef : null}
							className="aspect-video snap-center snap-always rounded-md object-cover"
							src={img.src}
							alt="nature"
							key={index}
						/>
					))}

					<div className="fixed inset-x-0 mx-auto flex w-full max-w-3xl items-center justify-between p-4 sm:p-4">
						<button
							onClick={() => changeCurrentImageIndex(-1)}
							className="flex items-center justify-center rounded-md bg-neutral-100 p-2 text-neutral-900 shadow-md disabled:opacity-70"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								strokeWidth={1.5}
								stroke="currentColor"
								className="h-6 w-6"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									d="M15.75 19.5L8.25 12l7.5-7.5"
								/>
							</svg>
						</button>

						<button
							onClick={() => changeCurrentImageIndex(1)}
							className="flex items-center justify-center rounded-md bg-neutral-100 p-2 text-neutral-900 shadow-md disabled:opacity-70"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								strokeWidth={1.5}
								stroke="currentColor"
								className="h-6 w-6"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									d="M8.25 4.5l7.5 7.5-7.5 7.5"
								/>
							</svg>
						</button>
					</div>
				</div>

				<div className="flex items-center gap-2">
					{images.map((_, index) => (
						<div
							className={`rounded-full ${
								imageIndex === index ? "bg-sky-500" : "bg-neutral-500"
							} p-1`}
							key={index}
						></div>
					))}
				</div>
			</main>
		</>
	);
}
